version: '3.8'

services:
  api:
    image: node:fermium
    container_name: splitbook-api
    working_dir: /usr/api
    command: bash -c "yarn && yarn db && yarn dev"
    ports:
      - 8085:8085
    depends_on:
      - postgresql
      - redis
    volumes:
      - ./src:/usr/api/src
      - ./package.json:/usr/api/package.json
      - ./tmp:/usr/api/tmp
      - ./yarn.lock:/usr/api/yarn.lock
      - ./knexfile.js:/usr/api/knexfile.js
    env_file:
      - .env
    environment:
      - DATABASE_HOST=postgresql
      - REDIS_HOST=redis
    restart: always
    networks:
      - splitbook_backend

  postgresql:
    image: bitnami/postgresql
    container_name: splitbook-postgresql
    environment:
      - POSTGRESQL_DATABASE=${DATABASE_NAME}
      - POSTGRESQL_USER=${DATABASE_USER}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - splitbook_backend

  redis:
    image: bitnami/redis
    container_name: splitbook-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 6379:6379
    restart: always
    networks:
      - splitbook_backend

volumes:
  postgresql_data:
    driver: local

networks:
  splitbook_backend:
