version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./Docker/api.Dockerfile
    container_name: api
    ports:
      - 8085:8085
    links:
      - redis
      - mssql

    depends_on:
      - mssql
      - redis
    restart: always

  mssql:
    build: 
      context: .
      dockerfile: ./Docker/mssql.Dockerfile
    container_name: mssql-server
    volumes:
      - mssql-data:/var/opt/mssql/data
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    restart: always

  redis:
    image: redis:alpine
    container_name: redis-server
    restart: always
    ports:
      - 6379:6379

volumes:
  mssql-data:
