FROM node:12.16.3

WORKDIR /home/node/app

COPY ./package*.json ./
RUN npm install

COPY ./ .

RUN chmod +x /home/node/app/scripts/api/run-initialization.sh

EXPOSE 8085

ARG DATABASE_USER
ARG NODE_ENV
ARG PORT
ARG DATABASE_SERVER
ARG REDIS_HOST
ARG REDIS_PORT

ENV DATABASE_USER ${DATABASE_USER}
ENV NODE_ENV ${NODE_ENV}
ENV PORT ${PORT}
ENV DATABASE_SERVER ${DATABASE_SERVER}
ENV REDIS_HOST ${REDIS_HOST}
ENV REDIS_PORT ${REDIS_PORT}

CMD /bin/bash ./scripts/api/entrypoint.sh
